### DISCUSSION TITLE
avoidLayoutShift and --ck-scrollbar-width how to use it?

### DISCUSSION THREAD

**Discussion by SimonVillage** [family/connectkit#70] [Q&A] [answered]
Every time I open the connect dialog, the scrollbars are disappearing and my layout is shifting.
When setting the Theme

```javascript
      <ConnectKitProvider
        options={{ avoidLayoutShift: false }}
        customTheme={{
          "--ck-scrollbar-width": "20",
        }}
      >
        {/* Your App */}
        <ConnectKitButton />
      </ConnectKitProvider>
```

It only adds a 0px value to the body. I think that I just have a misunderstanding how to use it properly.

**Comment by lochie** [comment, marked as answer]
@SimonHausdorf `avoidLayoutShift: false` will disable our handling of the layout shift, by default if this is set to `true` ConnectKit will handle this for you.

If you want to wish to provide your own solution by setting `avoidLayoutShift` to `false`, you will need to use the `--ck-scrollbar-width` (which ConnectKit generates) and use this somewhere in your css on the `html` or `body` selector.

**Example:**
```jsx
<ConnectKitProvider
  options={{ avoidLayoutShift: false }}
>
  {/* Your App */}
</ConnectKitProvider>
```
```scss
/* avoid shifting when scrollbar is visible */
html {
  padding-right: var(--ck-scrollbar-width);
}

/* avoid shifting fixed elements */
.fixed-header {
  position: fixed;
  top: 0;
  left: 0;
  right: var(--ck-scrollbar-width, 0); 
}
```
